version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment: MONGO_URI:mongodb+srv://stonebo0sh77:6auBxzMmGZt7tfCs@cluster0.6bixfen.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

volumes:
  mongo-data:
